export const FETCH_BOOKS_START = "FETCH_BOOKS_START";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAIL = "FETCH_BOOKS_FAIL";

export const FETCH_BOOK_START = "FETCH_BOOK_START";
export const FETCH_BOOK_SUCCESS = "FETCH_BOOK_SUCCESS";
export const FETCH_BOOK_FAIL = "FETCH_BOOK_FAIL";

export const DELETE_BOOK_START = "DELETE_BOOK_START";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL";

export const ADD_BOOK_START = "ADD_BOOK_START";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAIL = "ADD_BOOK_FAIL";

export const FETCH_AUTHORS_START = "FETCH_AUTHORS_START";
export const FETCH_AUTHORS_SUCCESS = "FETCH_AUTHORS_SUCCESS";
export const FETCH_AUTHORS_FAIL = "FETCH_AUTHORS_FAIL";

export const FETCH_AUTHOR_START = "FETCH_AUTHOR_START";
export const FETCH_AUTHOR_SUCCESS = "FETCH_AUTHOR_SUCCESS";
export const FETCH_AUTHOR_FAIL = "FETCH_AUTHOR_FAIL";

export const DELETE_AUTHOR_START = "DELETE_AUTHOR_START";
export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";
export const DELETE_AUTHOR_FAIL = "DELETE_AUTHOR_FAIL";

export const ADD_AUTHOR_START = "ADD_AUTHOR_START";
export const ADD_AUTHOR_SUCCESS = "ADD_AUTHOR_SUCCESS";
export const ADD_AUTHOR_FAIL = "ADD_AUTHOR_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
